# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site Information
title: Emran Poh
email: emranpoh@gmail.com
work_email: emranpoh@smu.edu.sg
description: >-
  HAI Researcher + Designer
baseurl: ""
url: ""
author: Emran Poh
year: 2025
location: Singapore
profile_image: /assets/images/me.jpeg

# Social Media
github_username: emranpoh
linkedin_username: emranpoh
instagram_username: emranpoh_
telegram_username: ehhhhmmmm
scholar_id: wYcrORkAAAAJ
# twitter_username: jekyllrb
# linkedin_username: your-linkedin-username

# Build Settings
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  posts:
    output: true
    permalink: /content/posts/:title/
    path: content/posts
  projects:
    output: true
    permalink: /projects/:name/
  publications:
    output: true
    permalink: /publications/:title/

# Default Front Matter
defaults:
  - scope:
      path: ""
    values:
      layout: "pages/default"
  - scope:
      path: "index.markdown"
    values:
      layout: "pages/default"
      permalink: /
  - scope:
      path: "content/posts"
      type: "posts"
    values:
      layout: "posts/post"
  - scope:
      path: "_content/projects"
      type: "projects"
    values:
      layout: "pages/project"
  - scope:
      path: "_content/publications"
      type: "publications"
    values:
      layout: "pages/publication"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .git/
  - .gitignore
  - README.md
