# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site Information
title: emran poh
email: emranpoh@gmail.com
description: >-
  UX Researcher, Designer, and Coder based in Singapore
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: Emran Poh
year: 2025

# Social Media
github_username: emranpoh
# twitter_username: jekyllrb
# linkedin_username: your-linkedin-username

# Build Settings
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  projects:
    output: true
  publications:
    output: true

# Default Front Matter
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.markdown"
    values:
      layout: "default"
      permalink: /
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .git/
  - .gitignore
  - README.md
